-- Diário de Aprendizagem — Jornada dos Saberes
-- Execute este arquivo uma única vez no SQL Editor do Supabase.

create table if not exists public.tentativas (
  id bigint generated by default as identity primary key,
  aluno_id uuid not null references public.alunos(id) on delete cascade,
  aventura text not null,
  questao_indice integer not null,
  questao_texto text not null,
  resposta_escolhida text not null,
  correta boolean not null,
  tentativa_numero integer not null default 1,
  usou_narracao boolean not null default false,
  tempo_resposta_seg integer not null default 0,
  criado_em timestamptz not null default now()
);

create index if not exists tentativas_aluno_id_idx on public.tentativas(aluno_id);
create index if not exists tentativas_aventura_idx on public.tentativas(aventura);

alter table public.tentativas enable row level security;

drop policy if exists "Professor consulta tentativas da sua turma" on public.tentativas;
create policy "Professor consulta tentativas da sua turma"
on public.tentativas for select
to authenticated
using (
  exists (
    select 1 from public.alunos a
    join public.turmas t on t.id = a.turma_id
    where a.id = tentativas.aluno_id
      and t.professora_id = auth.uid()
  )
);

drop policy if exists "Professor registra tentativas da sua turma" on public.tentativas;
create policy "Professor registra tentativas da sua turma"
on public.tentativas for insert
to authenticated
with check (
  exists (
    select 1 from public.alunos a
    join public.turmas t on t.id = a.turma_id
    where a.id = tentativas.aluno_id
      and t.professora_id = auth.uid()
  )
);

grant select, insert on public.tentativas to authenticated;
grant usage, select on sequence public.tentativas_id_seq to authenticated;
